import { Room } from "./room";
export type Hotel = {
  id: string;
  name: string;
  city: string;
  country: string;
  street: string;
  image: string[];
  price?: number;
  description: string;
  starRating: number;
  oldPrice: string;
  newPrice: string;
   reviewText: string;
  reviews: string;
  badge: string | null;
  nights: string;
isWeekendDeal:boolean;
 hasDiscount : boolean;
  rooms: Room[];
};